version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: raat
      POSTGRES_DB: jdbc
    ports:
      - "8888:8888"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: